# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RasterValueVectorizer
                                 A QGIS plugin
 Vectoriza un raster generando polígonos por valor único o rango de valores, ideal para análisis temático y clasificación.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-11-26
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Diener Chang
        email                : dienerchang@aerometricsgt.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .raster_value_vectorizer_dc_dialog import RasterValueVectorizerDialog
import os.path


class RasterValueVectorizer:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'RasterValueVectorizer_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&RasterValueVectorizer DC')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('RasterValueVectorizer', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/raster_value_vectorizer_dc/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Raster Value Vectorizer'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&RasterValueVectorizer DC'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""
        
        # Import processing and UI elements here to avoid circular dependencies or loading issues
        import tempfile
        import shutil
        import uuid
        from qgis import processing
        from qgis.core import (QgsProject, Qgis, QgsVectorLayer, QgsField, QgsFeature, 
                             QgsTask, QgsApplication, QgsProcessingFeedback, QgsProcessingContext, 
                             QgsMessageLog, QgsProcessingUtils)
        from qgis.PyQt.QtCore import QVariant, Qt
        from qgis.PyQt.QtWidgets import QMessageBox

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = RasterValueVectorizerDialog()

        # Refresh layers every time the dialog is shown
        self.dlg.populate_layers()

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # 1. Get Inputs
            layer = self.dlg.mMapLayerComboBox.currentData()
            is_temp = self.dlg.mCheckBoxTemp.isChecked()
            output_file_base = self.dlg.mLineEditOutput.text()
            method_idx = self.dlg.mComboBoxMethod.currentIndex() # 0 = Unique, 1 = Ranges
            
            use_mask = self.dlg.mGroupBoxMask.isChecked()
            mask_layer = self.dlg.mMapLayerComboBoxMask.currentData()
            
            calc_area_m2 = self.dlg.mCheckBoxAreaM2.isChecked()
            calc_area_ha = self.dlg.mCheckBoxAreaHa.isChecked()

            # Validation
            if not layer:
                self.iface.messageBar().pushMessage("Error", "Por favor seleccione una capa raster.", level=Qgis.Critical)
                return
            
            if not is_temp and not output_file_base:
                self.iface.messageBar().pushMessage("Error", "Por favor seleccione un archivo de salida o marque 'Capa temporal'.", level=Qgis.Critical)
                return
                
            if use_mask and not mask_layer:
                self.iface.messageBar().pushMessage("Error", "Seleccionó usar máscara pero no eligió ninguna capa.", level=Qgis.Critical)
                return

            # Create a dedicated temp directory for this run to avoid path issues
            # We use mkdtemp to ensure it exists and is writable
            current_temp_dir = tempfile.mkdtemp(prefix="raster_vectorizer_")

            # Prepare inputs for thread (ensure they are files)
            layer_source = layer.source()
            if not os.path.isfile(layer_source):
                self.iface.messageBar().pushMessage("Info", "Preparando capa raster para procesamiento...", level=Qgis.Info)
                temp_raster = os.path.join(current_temp_dir, 'input_raster.tif')
                processing.run("gdal:translate", {
                    'INPUT': layer,
                    'OUTPUT': temp_raster
                })
                layer_source = temp_raster

            mask_source = None
            if use_mask and mask_layer:
                mask_source = mask_layer.source()
                if not os.path.isfile(mask_source):
                    self.iface.messageBar().pushMessage("Info", "Preparando máscara para procesamiento...", level=Qgis.Info)
                    temp_mask = os.path.join(current_temp_dir, 'mask.gpkg')
                    processing.run("native:savefeatures", {
                        'INPUT': mask_layer,
                        'OUTPUT': temp_mask
                    })
                    mask_source = temp_mask

            # Gather parameters for background task
            params = {
                'layer_source': layer_source, 
                'layer_crs_authid': layer.crs().authid(),
                'mask_source': mask_source,
                'is_temp': is_temp,
                'output_file_base': output_file_base,
                'method_idx': method_idx,
                'unique_values': [],
                'ranges_table': [],
                'id_to_label_map': {},
                'calc_area_m2': calc_area_m2,
                'calc_area_ha': calc_area_ha,
                'temp_dir': current_temp_dir
            }

            if method_idx == 0: # Unique Values
                # Get values from list widget
                count = self.dlg.mListWidgetUnique.count()
                if count == 0:
                    self.iface.messageBar().pushMessage("Error", "Agregue al menos un valor único a la lista.", level=Qgis.Critical)
                    return
                for i in range(count):
                    try:
                        val = float(self.dlg.mListWidgetUnique.item(i).text())
                        params['unique_values'].append(val)
                    except ValueError:
                        pass
            
            else: # Ranges
                rows = self.dlg.mTableWidgetRanges.rowCount()
                if rows == 0:
                    self.iface.messageBar().pushMessage("Error", "Defina al menos un rango.", level=Qgis.Critical)
                    return

                current_id = 1
                for r in range(rows):
                    try:
                        min_val = float(self.dlg.mTableWidgetRanges.item(r, 0).text())
                        max_val = float(self.dlg.mTableWidgetRanges.item(r, 1).text())
                        raw_cls_val = self.dlg.mTableWidgetRanges.item(r, 2).text()
                        
                        internal_id = current_id
                        params['id_to_label_map'][internal_id] = raw_cls_val
                        current_id += 1
                        
                        params['ranges_table'].extend([min_val, max_val, internal_id])
                    except (ValueError, AttributeError):
                            self.iface.messageBar().pushMessage("Error", f"Valores numéricos inválidos en Min/Max en la fila {r+1}", level=Qgis.Critical)
                            return

            # Define the task function
            def run_vectorization(task, params):
                from qgis import processing
                from qgis.core import QgsCoordinateReferenceSystem, QgsProcessingContext, QgsProcessingFeedback
                
                # Custom feedback class to update task progress
                class TaskFeedback(QgsProcessingFeedback):
                    def __init__(self, task):
                        super().__init__()
                        self.task = task
                    
                    def setProgress(self, progress):
                        self.task.setProgress(progress)
                        
                    def reportError(self, error, fatalError=False):
                        QgsMessageLog.logMessage(f"Processing Error: {error}", "RasterValueVectorizer", Qgis.Critical)

                try:
                    feedback = TaskFeedback(task)
                    context = QgsProcessingContext()
                    # Set project instance to ensure ellipsoidal area calculation if available
                    context.setProject(QgsProject.instance())
                    
                    task.setProgress(0)
                    QgsMessageLog.logMessage("Iniciando proceso de vectorización...", "RasterValueVectorizer", Qgis.Info)
                    
                    # Step 0: Clip if needed (once for all)
                    input_raster_for_calc = params['layer_source']
                    crs = QgsCoordinateReferenceSystem(params['layer_crs_authid'])
                    
                    if params['mask_source']:
                        QgsMessageLog.logMessage("Recortando raster...", "RasterValueVectorizer", Qgis.Info)
                        # Use UUID to ensure unique temp files
                        temp_clip = os.path.join(params['temp_dir'], f'clipped_{uuid.uuid4().hex}.tif')
                        
                        clip_params = {
                            'INPUT': params['layer_source'],
                            'MASK': params['mask_source'],
                            'SOURCE_CRS': crs,
                            'TARGET_CRS': crs,
                            'KEEP_RESOLUTION': True,
                            'NODATA': 0,
                            'ALPHA_BAND': False,
                            'CROP_TO_CUTLINE': True,
                            'DATA_TYPE': 0, 
                            'OUTPUT': temp_clip
                        }
                        processing.run("gdal:cliprasterbymasklayer", clip_params, context=context, feedback=feedback)
                        input_raster_for_calc = temp_clip
                    
                    if task.isCanceled(): return None

                    output_layers = []

                    # Helper to process one item
                    def process_one(target_val=None, ranges_table=None, suffix=""):
                        temp_processed = os.path.join(params['temp_dir'], f'processed_{uuid.uuid4().hex}.tif')
                        
                        # Use reclassifybytable for BOTH unique and ranges for consistency and robustness
                        table_to_use = []
                        if target_val is not None:
                            # Create a table for exact match: min=val, max=val, class=1
                            # Using inclusive bounds (Range boundaries = 2: min <= val <= max)
                            table_to_use = [target_val, target_val, 1]
                        else:
                            table_to_use = ranges_table

                        reclass_params = {
                            'INPUT_RASTER': input_raster_for_calc,
                            'RASTER_BAND': 1,
                            'TABLE': table_to_use,
                            'NO_DATA': 0,
                            'RANGE_BOUNDARIES': 2, # min <= value <= max
                            'NODATA_FOR_MISSING': True, # Important: everything else becomes nodata
                            'DATA_TYPE': 5, # Int
                            'OUTPUT': temp_processed
                        }
                        processing.run("native:reclassifybytable", reclass_params, context=context, feedback=feedback)

                        # Logic to chain operations and avoid overwriting files in place
                        # 1. Polygonize -> Temp1
                        # 2. Calc M2 -> Temp2 (or Final)
                        # 3. Calc Ha -> Final
                        
                        # Determine the final destination
                        final_output_path = ""
                        if params['is_temp']:
                             final_output_path = os.path.join(params['temp_dir'], f'vectorized_{suffix}_{uuid.uuid4().hex}.gpkg')
                        else:
                             base, ext = os.path.splitext(params['output_file_base'])
                             if suffix:
                                 final_output_path = f"{base}{suffix}.gpkg"
                             else:
                                 final_output_path = f"{base}.gpkg"
                             final_output_path = os.path.normpath(final_output_path)

                        # Determine intermediate steps
                        steps = ['polygonize']
                        # Add labeling step if needed (Ranges method)
                        if params['method_idx'] == 1 and params['id_to_label_map']:
                            steps.append('labels')
                        
                        if params['calc_area_m2']: steps.append('m2')
                        if params['calc_area_ha']: steps.append('ha')
                        
                        current_input_vector = None
                        
                        for i, step in enumerate(steps):
                            is_last_step = (i == len(steps) - 1)
                            
                            # Output for this step
                            if is_last_step:
                                step_output = final_output_path
                            else:
                                step_output = os.path.join(params['temp_dir'], f'step_{step}_{uuid.uuid4().hex}.gpkg')
                            
                            # Delete if exists (crucial for the final step if overwriting user file)
                            if os.path.exists(step_output):
                                try:
                                    os.remove(step_output)
                                except:
                                    pass
                                    
                            if step == 'polygonize':
                                QgsMessageLog.logMessage(f"Vectorizando a: {step_output}", "RasterValueVectorizer", Qgis.Info)
                                poly_params = {
                                    'INPUT': temp_processed,
                                    'BAND': 1,
                                    'FIELD': 'class_id',
                                    'EIGHT_CONNECTEDNESS': False,
                                    'OUTPUT': step_output
                                }
                                processing.run("gdal:polygonize", poly_params, context=context, feedback=feedback)
                                current_input_vector = step_output

                            elif step == 'labels':
                                QgsMessageLog.logMessage(f"Aplicando etiquetas a: {step_output}", "RasterValueVectorizer", Qgis.Info)
                                # Construct CASE WHEN expression
                                expression_parts = ["CASE"]
                                for c_id, label in params['id_to_label_map'].items():
                                    safe_label = str(label).replace("'", "''")
                                    expression_parts.append(f"WHEN \"class_id\" = {c_id} THEN '{safe_label}'")
                                expression_parts.append("END")
                                expression = " ".join(expression_parts)

                                processing.run("native:fieldcalculator", {
                                    'INPUT': current_input_vector,
                                    'FIELD_NAME': 'etiqueta',
                                    'FIELD_TYPE': 2, # String
                                    'FIELD_LENGTH': 255,
                                    'FIELD_PRECISION': 0,
                                    'FORMULA': expression,
                                    'OUTPUT': step_output
                                }, context=context, feedback=feedback)
                                current_input_vector = step_output
                                
                            elif step == 'm2':
                                QgsMessageLog.logMessage(f"Calculando área m2 a: {step_output}", "RasterValueVectorizer", Qgis.Info)
                                processing.run("native:fieldcalculator", {
                                    'INPUT': current_input_vector,
                                    'FIELD_NAME': 'area_m2',
                                    'FIELD_TYPE': 0, # Float
                                    'FIELD_LENGTH': 20,
                                    'FIELD_PRECISION': 6, # Increased precision
                                    'FORMULA': '$area',
                                    'OUTPUT': step_output
                                }, context=context, feedback=feedback)
                                current_input_vector = step_output
                                
                            elif step == 'ha':
                                QgsMessageLog.logMessage(f"Calculando área ha a: {step_output}", "RasterValueVectorizer", Qgis.Info)
                                processing.run("native:fieldcalculator", {
                                    'INPUT': current_input_vector,
                                    'FIELD_NAME': 'area_ha',
                                    'FIELD_TYPE': 0, # Float
                                    'FIELD_LENGTH': 20,
                                    'FIELD_PRECISION': 4, # Precision 4
                                    'FORMULA': '$area / 10000',
                                    'OUTPUT': step_output
                                }, context=context, feedback=feedback)
                                current_input_vector = step_output

                        return final_output_path

                    # Execution Loop
                    if params['method_idx'] == 0: # Unique Values
                        for val in params['unique_values']:
                            if task.isCanceled(): return None
                            QgsMessageLog.logMessage(f"Procesando valor: {val}...", "RasterValueVectorizer", Qgis.Info)
                            # Clean suffix for filename
                            suffix = f"_{str(val).replace('.', '_')}"
                            out = process_one(target_val=val, suffix=suffix)
                            output_layers.append({'path': out, 'name': f"Valor_{val}"})
                    else: # Ranges
                        if task.isCanceled(): return None
                        QgsMessageLog.logMessage("Procesando rangos...", "RasterValueVectorizer", Qgis.Info)
                        out = process_one(ranges_table=params['ranges_table'])
                        output_layers.append({'path': out, 'name': "Rangos"})

                    return output_layers

                except Exception as e:
                    QgsMessageLog.logMessage(f"Excepción en worker: {str(e)}", "RasterValueVectorizer", Qgis.Critical)
                    return Exception(str(e))

            # Callback when task finishes
            def on_finished(exception, result=None):
                if exception:
                    QMessageBox.critical(self.iface.mainWindow(), "Error", f"Ocurrió un error crítico: {str(exception)}")
                    return
                    
                if isinstance(result, Exception):
                    QMessageBox.critical(self.iface.mainWindow(), "Error", f"Error en el procesamiento: {str(result)}")
                    return
                    
                if result:
                    # Load Results
                    loaded_count = 0
                    for res in result:
                        try:
                            path = res['path']
                            name = res['name']
                            if params['is_temp']:
                                name += " (Temp)"
                            
                            if os.path.exists(path):
                                final_layer = self.iface.addVectorLayer(path, name, "ogr")
                                if final_layer and final_layer.isValid():
                                    loaded_count += 1
                        except Exception as e:
                             QgsMessageLog.logMessage(f"Error cargando capa {res['name']}: {str(e)}", "RasterValueVectorizer", Qgis.Warning)

                    if loaded_count > 0:
                        QMessageBox.information(self.iface.mainWindow(), "Éxito", f"Proceso completado. Se cargaron {loaded_count} capas.")
                    else:
                        QMessageBox.warning(self.iface.mainWindow(), "Advertencia", "El proceso terminó pero no se cargaron capas.")
                else:
                    QMessageBox.warning(self.iface.mainWindow(), "Aviso", "El proceso terminó sin resultados.")
                
                # Clean up the temporary directory ONLY if we are NOT using it for the final result
                if not params['is_temp'] and os.path.exists(params['temp_dir']):
                    try:
                        shutil.rmtree(params['temp_dir'])
                    except:
                        pass # Best effort

            # Create and start the task
            # Create and start the task
            try:
                task = QgsTask.fromFunction("Vectorizando Raster", run_vectorization, on_finished=on_finished, params=params)
                QgsApplication.taskManager().addTask(task)
                self.iface.messageBar().pushMessage("Info", "Procesamiento iniciado en segundo plano. Espere...", level=Qgis.Info)
            except Exception as e:
                QMessageBox.critical(self.iface.mainWindow(), "Error", f"No se pudo iniciar la tarea: {str(e)}")

